# Book settings
title: ESE532 Handouts Fall 2020
author: Department of Electrical and Systems Engineering, UPenn
logo: common/logo.png
repository:
  url: https://github.com/icgrp/ese532_handouts
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
exclude_patterns:
  - common/*
  - hw2/*
  - hw3/*
  - hw4/*
  - hw5/*
  - hw6/*
  - hw7/*
  - project/*

latex:
  latex_documents:
    targetname: book.tex
